server:
  port: 8080
spring:
  elasticsearch:
    uris: "https://69c630a3d3844e7b934261af9a184aa4.me-south-1.aws.elastic-cloud.com:9243"
    username: book_store
    password: iGtHBTAi94uf9dp
  data:
    elasticsearch:
      repositories:
        enabled: true

bezkoder:
  app:
    jwtSecret: ======================BezKoder=Spring===========================
    jwtExpirationMs: 86400000

logging:
  level:
    org:
      springframework: INFO