server:
  port: 8080
spring:
  elasticsearch:
    uris: "localhost:9200"
    username: elastic
    password: 0ZQ9hNjmAyO7oa8ruQxl
  data:
    elasticsearch:
      repositories:
        enabled: true

