server:
  port: 8080
spring:
  elasticsearch:
    uris: "localhost:9200"
    username: elastic
    password: 0ZQ9hNjmAyO7oa8ruQxl
  data:
    elasticsearch:
      repositories:
        enabled: true

bezkoder:
  app:
    jwtSecret: ======================BezKoder=Spring===========================
    jwtExpirationMs: 86400000

logging:
  level:
    org:
      springframework: INFO