server:
  port: 8080
spring:
  elasticsearch:
    uris: "https://e6b49034e8594494a6fd75f75c5d7aca.us-central1.gcp.cloud.es.io:443"
    username: book_store
    password: 0ZQ9hNjmAyO7oa8ruQxl
  data:
    elasticsearch:
      repositories:
        enabled: true

bezkoder:
  app:
    jwtSecret: ======================BezKoder=Spring===========================
    jwtExpirationMs: 86400000

logging:
  level:
    org:
      springframework: INFO